backend_url: https://jsonplaceholder.typicode.com

management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - metrics

logging:
  file:
    name: api_service.log
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
    root: INFO
  pattern:
    console: '%d{"yyyy/MM/dd HH:mm:ss,SSS"} [%p] [%t] [request_id:%X{request_id}] - %msg%n'
    file:    '%d{"yyyy/MM/dd HH:mm:ss,SSS"} [%p] [%t] [request_id:%X{request_id}] - %msg%n'